name: Quality Assurance

on:
  push:
  pull_request:

jobs:
  build-macos:
    name: macOS (${{ matrix.configure.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
        configure:
          - {label: "with parser generation _AND_ PCRE2", opt: "--enable-parser-generation --with-pcre2" }
    steps:
      - name: Setup Dependencies
        # curl, pcre2 not installed because they're already
        # included in the image
        run: |
          brew install autoconf \
                       automake \
                       libtool \
                       yajl \
                       lmdb \
                       lua \
                       libmaxminddb \
                       libxml2 \
                       geoip \
                       ssdeep \
                       pcre \
                       bison \
                       flex
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: build.sh
        run: ./build.sh
      - name: configure
        run: ./configure ${{ matrix.configure.opt }} --enable-assertions=yes
      - uses: ammaraskar/gcc-problem-matcher@master
      - name: make
        run: make -j `sysctl -n hw.logicalcpu`
      - name: check
        run: make check

